import { AnimeMangaGenres } from './anime-manga-genres';
export interface AnimeTop {
    mal_id: number,
    url: string,
    image_url: string,
    trailer_url: string,
    title: string,
    title_english: string,
    title_japanese: string,
    title_synonyms: string,
    type: string,
    volumes: number,
    chapters: number,
    source: string,
    episodes: number,
    string: string,
    duration: string,
    rating: string,
    score: number,
    popularity: number,
    synopsis: string,
    background: string,
    producers: AnimeMangaGenres[],
    licensors: [],
    studios: [],
    genres: AnimeMangaGenres[],
    opening_themes: [],
    ending_themes: []
}
